### Signup
POST http://localhost:4000/users/signup
Content-Type: application/json

{
  "email": "email2@email.fr",
  "username": "tes2",
  "password": "test2"
}

### Signin
POST http://localhost:4000/users/signin
Content-Type: application/json

{
  "username": "tes2",
  "password": "test2"
}
